version: '3.3'

services:
   wordpress:
     depends_on:
       - db
       - memcached
     image: docker.io/bitpoke/wordpress-runtime:bedrock
     volumes:
       - ./:/app
     ports:
      - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: root
       WORDPRESS_DB_PASSWORD: root
       WORDPRESS_DB_NAME: wordpress
       MEMCACHED_HOST: memcached:11211
       WP_HOME: http://localhost:8080
       WP_SITEURL: http://localhost:8080/wp
       WP_ENV: development

   db:
     image: percona:5.7    
     command: --max_allowed_packet=32505856
     restart: always
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_ROOT_PASSWORD: root
     ports:
      - "3306:3306"

   memcached:
     image: memcached:1.5

volumes:
    db_data: {}